import * as React from "react";
import { cx } from "./types";
import { Input } from "./form";

export function FormField({ label, required, error, children }: { label: string; required?: boolean; error?: string; children: React.ReactNode }) { return <div className="ui-field"><div className="ui-field__label">{label}{required ? " *" : ""}</div>{children}{error ? <p className="ui-field__error" role="alert">{error}</p> : null}</div>; }
export function SearchField({ value, onChange, placeholder = "Search" }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <Input aria-label={placeholder} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} type="search" />; }
export function Accordion({ items }: { items: readonly { id: string; title: string; content: React.ReactNode }[] }) { const [open, setOpen] = React.useState<string | null>(items[0]?.id ?? null); return <div className="ui-accordion">{items.map(item => <section key={item.id} className="ui-accordion__item"><h3><button type="button" aria-expanded={open === item.id} aria-controls={`panel-${item.id}`} onClick={() => setOpen(open === item.id ? null : item.id)}>{item.title}</button></h3><div id={`panel-${item.id}`} hidden={open !== item.id} className="ui-accordion__panel">{item.content}</div></section>)}</div>; }
export function Drawer({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: React.ReactNode }) { React.useEffect(() => { if (!open) return; const handler = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [open, onClose]); if (!open) return null; return <div className="ui-drawer__backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><aside className="ui-drawer" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button type="button" className="ui-icon-button" onClick={onClose} aria-label="Close">×</button></header><div className="ui-drawer__content">{children}</div></aside></div>; }
export function Toast({ title, message, onClose }: { title: string; message?: string; onClose?: () => void }) { return <div className="ui-toast" role="status" aria-live="polite"><div><strong>{title}</strong>{message ? <p>{message}</p> : null}</div>{onClose ? <button type="button" onClick={onClose} aria-label="Close notification">×</button> : null}</div>; }
export function DropdownMenu({ label, items }: { label: string; items: readonly { label: string; onSelect: () => void; disabled?: boolean }[] }) { const [open, setOpen] = React.useState(false); return <div className="ui-dropdown"><button type="button" aria-expanded={open} onClick={() => setOpen(v => !v)}>{label}</button>{open ? <div className="ui-dropdown__menu" role="menu">{items.map(item => <button key={item.label} type="button" role="menuitem" disabled={item.disabled} onClick={() => { item.onSelect(); setOpen(false); }}>{item.label}</button>)}</div> : null}</div>; }
export function CommandPalette({ open, onClose, items }: { open: boolean; onClose: () => void; items: readonly { label: string; onSelect: () => void }[] }) { React.useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; if (open) document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [open, onClose]); if (!open) return null; return <div className="ui-command__backdrop"><div className="ui-command" role="dialog" aria-modal="true" aria-label="Command menu"><Input aria-label="Search commands" autoFocus placeholder="Search commands" /><div role="listbox">{items.map(item => <button key={item.label} type="button" onClick={item.onSelect}>{item.label}</button>)}</div></div></div>; }
