import * as React from "react";
import { Badge, Card, CardContent, CardHeader, CardTitle } from "@ui-platform/components";
import { DataTable, LineChart } from "@ui-platform/blocks";

export function DomainMetric({ label, value, delta, tone = "success" }: { label: string; value: string; delta?: string; tone?: "success" | "warning" | "danger" | "info" }) { return <Card><CardHeader><CardTitle>{label}</CardTitle></CardHeader><CardContent><div className="ui-domain-metric__value">{value}</div>{delta ? <Badge tone={tone}>{delta}</Badge> : null}</CardContent></Card>; }
export function CrmPipeline({ stages }: { stages: readonly { label: string; count: number }[] }) { return <Card><CardHeader><CardTitle>CRM Pipeline</CardTitle></CardHeader><CardContent><div className="ui-pipeline">{stages.map(stage => <div className="ui-pipeline__stage" key={stage.label}><span>{stage.label}</span><strong>{stage.count}</strong></div>)}</div></CardContent></Card>; }
export function FinanceSummary({ revenue, expenses, cash }: { revenue: string; expenses: string; cash: string }) { return <div className="ui-domain-grid"><DomainMetric label="Revenue" value={revenue} delta="+8.2%" /><DomainMetric label="Expenses" value={expenses} delta="+2.1%" tone="warning" /><DomainMetric label="Cash balance" value={cash} delta="Healthy" tone="info" /></div>; }
export function BillingSummary({ invoices, overdue }: { invoices: number; overdue: number }) { return <div className="ui-domain-grid"><DomainMetric label="Invoices" value={String(invoices)} /><DomainMetric label="Overdue" value={String(overdue)} delta={overdue ? "Action required" : "Clear"} tone={overdue ? "danger" : "success"} /></div>; }
export function PaymentStatus({ successRate }: { successRate: number }) { return <DomainMetric label="Payment success rate" value={`${successRate}%`} delta="30 day" tone="success" />; }
export function MonitoringOverview({ data }: { data: readonly { label: string; value: number }[] }) { return <Card><CardHeader><CardTitle>Monitoring throughput</CardTitle></CardHeader><CardContent><div className="ui-chart ui-chart--domain"><LineChart data={data} label="Monitoring throughput" /></div></CardContent></Card>; }
export function NmsHealth({ devices, alarms }: { devices: number; alarms: number }) { return <div className="ui-domain-grid"><DomainMetric label="Devices online" value={String(devices)} delta="Operational" /><DomainMetric label="Active alarms" value={String(alarms)} delta={alarms ? "Review" : "Clear"} tone={alarms ? "warning" : "success"} /></div>; }
export function InventorySummary({ skuCount, lowStock }: { skuCount: number; lowStock: number }) { return <div className="ui-domain-grid"><DomainMetric label="SKU" value={String(skuCount)} /><DomainMetric label="Low stock" value={String(lowStock)} tone={lowStock ? "warning" : "success"} /></div>; }
export function ErpSummary({ orders, fulfillment }: { orders: number; fulfillment: number }) { return <div className="ui-domain-grid"><DomainMetric label="Orders" value={String(orders)} /><DomainMetric label="Fulfillment" value={`${fulfillment}%`} tone="success" /></div>; }
export function HrmSummary({ headcount, openRoles }: { headcount: number; openRoles: number }) { return <div className="ui-domain-grid"><DomainMetric label="Headcount" value={String(headcount)} /><DomainMetric label="Open roles" value={String(openRoles)} tone="info" /></div>; }
export function CmsSummary({ published, drafts }: { published: number; drafts: number }) { return <div className="ui-domain-grid"><DomainMetric label="Published" value={String(published)} /><DomainMetric label="Drafts" value={String(drafts)} /></div>; }
export function GisSummary({ locations, coverage }: { locations: number; coverage: number }) { return <div className="ui-domain-grid"><DomainMetric label="Locations" value={String(locations)} /><DomainMetric label="Coverage" value={`${coverage}%`} /></div>; }
export function OmniChatSummary({ openConversations, sla }: { openConversations: number; sla: number }) { return <div className="ui-domain-grid"><DomainMetric label="Open conversations" value={String(openConversations)} /><DomainMetric label="SLA" value={`${sla}%`} tone={sla > 95 ? "success" : "warning"} /></div>; }
export function OssSummary({ deployments, incidents }: { deployments: number; incidents: number }) { return <div className="ui-domain-grid"><DomainMetric label="Deployments" value={String(deployments)} /><DomainMetric label="Incidents" value={String(incidents)} tone={incidents ? "danger" : "success"} /></div>; }
export function LogSummary({ events, errors }: { events: number; errors: number }) { return <div className="ui-domain-grid"><DomainMetric label="Events" value={String(events)} /><DomainMetric label="Errors" value={String(errors)} tone={errors ? "danger" : "success"} /></div>; }
export function AuditTable({ rows }: { rows: readonly { id: string; actor: string; action: string; time: string }[] }) { return <DataTable getRowId={row => row.id} rows={rows} columns={[{ key: "actor", header: "Actor" }, { key: "action", header: "Action" }, { key: "time", header: "Time" }]} />; }
